name: pr-preview

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  manage-preview-environment:
    uses: oncoursesystems/workflows/.github/workflows/pr-preview.yml@main
    with:
      runs-on: linux
      base-url: yourdomain.com
      environments: "['devel']"
      env-values-path: ./github/examples/errata/pr-previews
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
    permissions:
      contents: read
      packages: write
      pull-requests: write