name: web-ci

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        default: linux
      runs-on-windows:
        type: string
        default: self-hosted
      sparse-checkout:
        type: string
        required: false
      dotnet-version:
        type: string
        default: 8.0.x
      dotnet-project-path:
        type: string
        required: false
      dotnet-framework-project-path:
        type: string
        required: false
      dotnet-project-file:
        type: string
        required: false
      bun-version:
        type: string
        default: latest
      nodejs-version:
        type: string
        default: 20.x
      nodejs-project-path:
        type: string
        required: false
      dotnet-locked-mode:
        type: boolean
        default: false

env:
  DOTNET_INSTALL_DIR: "./.dotnet"
  DOTNET_CLI_HOME: "/tmp"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  CI: 1

jobs:
  build-nodejs:
    if: inputs.nodejs-project-path != ''
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v6
        with:
          sparse-checkout: ${{ inputs.sparse-checkout }}

      - name: ⚙️ Setup NodeJS
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ inputs.bun-version }}

      - name: 🏦 Cache dependencies
        id: cache-bun
        uses: actions/cache@v5
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles(format('{0}/bun.lock', inputs.nodejs-project-path)) }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: 📦 Install dependencies
        working-directory: ${{ inputs.nodejs-project-path }}
        run: bun install --frozen-lockfile

      - name: 🚀 Bun run build
        working-directory: ${{ inputs.nodejs-project-path }}
        run: bun run build

  build-dotnet-core:
    if: inputs.dotnet-project-path != ''
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v6
        with:
          sparse-checkout: ${{ inputs.sparse-checkout }}

      - name: ⚙️ Setup Dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
          cache: true
          cache-dependency-path: ${{ inputs.dotnet-project-path }}/**/*.csproj

      - name: 📦 Dotnet restore (locked mode)
        if: inputs.dotnet-locked-mode
        working-directory: ${{ inputs.dotnet-project-path }}
        env:
          GITHUB_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: dotnet restore --locked-mode

      - name: 🚀 Dotnet build
        working-directory: ${{ inputs.dotnet-project-path }}
        env:
          GITHUB_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: dotnet build --nologo --configuration Release ${{ inputs.dotnet-locked-mode && '--no-restore' || '' }}

  build-dotnet-framework:
    if: inputs.dotnet-framework-project-path != ''
    runs-on: ${{ inputs.runs-on-windows }}
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v6
        with:
          sparse-checkout: ${{ inputs.sparse-checkout }}

      - name: ⚙️ Setup MSBuild
        uses: microsoft/setup-msbuild@v3

      - name: ⚙️ Setup Nuget
        uses: nuget/setup-nuget@v4

      - name: 📦 Restore packages
        working-directory: ${{ inputs.dotnet-framework-project-path }}
        run: nuget restore ${{ inputs.dotnet-project-file }} ${{ inputs.dotnet-locked-mode && '-LockedMode' || '' }}

      - name: 🚀 Dotnet build
        working-directory: ${{ inputs.dotnet-framework-project-path }}
        run: msbuild ${{ inputs.dotnet-project-file }} /nologo /nr:false /p:platform="Any CPU" /p:configuration="Release"